config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/login')

  constraints :format => 'html' do
    as :user do
      get 'login' => 'devise/sessions#new'
    end

    devise_for :users, only: :sessions
    devise_for :admins, only: :sessions

    authenticate :admin do

      devise_for :users, skip: :sessions
      devise_for :admins, skip: :sessions
      resources :enterprises, except: [:edit, :update]
    end

    authenticate :user do
      resources :notifications
      resources :devices
      resources :feeds
      resources :masks
      resources :agendas
      resources :enterprises, only: [:edit, :update]
      get 'info' => 'enterprises#edit', as: :info
    end
  end

  apipie

  namespace :api, defaults: {format: 'json'} do
    get 'enterprises/:enterprise_id/feed' => 'enterprises#feed'
    get 'enterprises/:enterprise_id/agenda' => 'enterprises#agenda'
    get 'enterprises/:enterprise_id/masks' => 'enterprises#masks'
    get 'enterprises/:enterprise_id/notifications' => 'enterprises#notifications'
    get 'enterprises/:enterprise_id/info' => 'enterprises#info'
    post 'enterprises/:enterprise_id/devices' => 'enterprises#new_device'
  end
end

app/models/mask.rb
class Mask < ActiveRecord::Base
  belongs_to :enterprise
end

app/controllers/masks_controller.rb
class MasksController < ApplicationController
  before_action :set_mask, only: [:show, :edit, :update, :destroy]

  # GET /masks
  # GET /masks.json
  def index
    @masks = current_user.enterprise.masks
  end

  # GET /masks/1
  # GET /masks/1.json
  def show
  end

  # GET /masks/new
  def new
    @mask = Mask.new
  end

  # GET /masks/1/edit
  def edit
  end

  # POST /masks
  # POST /masks.json
  def create
    @mask = Mask.new(mask_params)
    @mask.enterprise = current_user.enterprise

    respond_to do |format|
      if @mask.save
        format.html { redirect_to @mask, notice: 'Mask was successfully created.' }
        format.json { render :show, status: :created, location: @mask }
      else
        format.html { render :new }
        format.json { render json: @mask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masks/1
  # PATCH/PUT /masks/1.json
  def update
    respond_to do |format|
      if @mask.update(mask_params)
        format.html { redirect_to @mask, notice: 'Mask was successfully updated.' }
        format.json { render :show, status: :ok, location: @mask }
      else
        format.html { render :edit }
        format.json { render json: @mask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masks/1
  # DELETE /masks/1.json
  def destroy
    @mask.destroy
    respond_to do |format|
      format.html { redirect_to masks_url, notice: 'Mask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mask
      @mask = Mask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mask_params
      params.require(:mask).permit(:enterprise_id, :imageUrl, :thumbUrl)
    end
end

app/helpers/masks_helper.rb
module MasksHelper
end

app/views/masks/_form.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for(@mask) do |f| %>
        <% if @mask.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@mask.errors.count, "error") %> prohibited this mask from being saved:</h2>

              <ul>
                <% @mask.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :imageUrl %><br>
          <%= f.text_field :imageUrl , class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :thumbUrl %><br>
          <%= f.text_field :thumbUrl , class: 'form-control'%>
        </div>

        <div class="form-group">
          <%= f.submit 'Save Mask', class: 'btn btn-success'%>
        </div>
    <% end %>
  </div>
</div>

app/views/masks/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Edit Mask
      <small>Edit Mask</small>
    </h1>
    <p id="notice"><%= notice %></p>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-dashboard"></i>  <%= link_to 'Masks', masks_path %>
      </li>
      <li class="active">
        <i class="fa fa-file"></i> Edit Mask
      </li>
    </ol>
  </div>
</div>

<%= render 'form' %>

app/views/masks/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Listing Masks
      <small>Listing Masks</small>
    </h1>
    <p id="notice"><%= notice %></p>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-dashboard"></i>  <%= link_to 'Masks', masks_path %>
      </li>
      <li class="active">
        <i class="fa fa-file"></i> Listing Masks
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th>Image</th>
          <th>Thumb</th>
          <th colspan="3">Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @masks.each do |mask| %>
            <tr>
              <td><img src="<%= mask.imageUrl %>"></td>
              <td><img src="<%= mask.thumbUrl %>"></td>
              <td><%= link_to 'Show', mask , class: 'btn btn-info'%></td>
              <td><%= link_to 'Edit', edit_mask_path(mask) , class: 'btn btn-warning'%></td>
              <td><%= link_to 'Destroy', mask, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger'%></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Mask', new_mask_path , class: 'btn btn-default'%>
    </div>
  </div>
</div>

app/views/masks/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      New Mask
      <small>New Mask</small>
    </h1>
    <p id="notice"><%= notice %></p>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-dashboard"></i>  <%= link_to 'Masks', masks_path %>
      </li>
      <li class="active">
        <i class="fa fa-file"></i> New Mask
      </li>
    </ol>
  </div>
</div>

<%= render 'form' %>

app/views/masks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Enterprise:</strong>
  <%= @mask.enterprise %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @mask.imageUrl %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @mask.thumbUrl %>
</p>

<%= link_to 'Edit', edit_mask_path(@mask) %> |
<%= link_to 'Back', masks_path %>