config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/login')

  constraints :format => 'html' do
    as :user do
      get 'login' => 'devise/sessions#new'
    end

    devise_for :users, only: :sessions
    devise_for :admins, only: :sessions

    authenticate :admin do

      devise_for :users, skip: :sessions
      devise_for :admins, skip: :sessions
      resources :enterprises, except: [:edit, :update]
    end

    authenticate :user do
      resources :notifications
      resources :devices
      resources :feeds
      resources :masks
      resources :agendas
      resources :enterprises, only: [:edit, :update]
      get 'info' => 'enterprises#edit', as: :info
    end
  end

  apipie

  namespace :api, defaults: {format: 'json'} do
    get 'enterprises/:enterprise_id/feed' => 'enterprises#feed'
    get 'enterprises/:enterprise_id/agenda' => 'enterprises#agenda'
    get 'enterprises/:enterprise_id/masks' => 'enterprises#masks'
    get 'enterprises/:enterprise_id/notifications' => 'enterprises#notifications'
    get 'enterprises/:enterprise_id/info' => 'enterprises#info'
    post 'enterprises/:enterprise_id/devices' => 'enterprises#new_device'
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :enterprise
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    # @notifications = Notification.order(date: :asc)
    @notifications = current_user.enterprise.notifications.order(date: :asc)
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)
    @notification.date = DateTime.now
    @notification.enterprise = current_user.enterprise

    respond_to do |format|
      if @notification.save

        sns = Aws::SNS::Client.new
        iphone_notification = {
            aps: {
                alert: notification_params[:text], sound: "default", badge: 1
            }
        }

        sns_message = {
            default: notification_params[:text],
            APNS_SANDBOX: iphone_notification.to_json,
            APNS: iphone_notification.to_json
        }

        sns.publish(topic_arn: 'arn:aws:sns:sa-east-1:831650654153:shed_app', message: sns_message.to_json, message_structure:"json")

        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:enterprise_id, :text, :date)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for(@notification) do |f| %>
        <% if @notification.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being
                saved:</h2>

              <ul>
                <% @notification.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :text %><br>
          <%= f.text_field :text, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Send Notification', class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>
</div>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Listing Notifications
      <small>Listing Notifications</small>
    </h1>
    <p id="notice"><%= notice %></p>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-dashboard"></i>  <%= link_to 'Notifications', notifications_path %>
      </li>
      <li class="active">
        <i class="fa fa-file"></i> Listing Notifications
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th>Text</th>
          <th>Date</th>
          <th colspan="3">Action</th>
        </tr>
        </thead>

        <tbody>
        <% @notifications.each do |notification| %>
            <tr>
              <td><%= notification.text %></td>
              <td><%= notification.date %></td>
              <td><%= link_to 'Show', notification, class: 'btn btn-info' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <br>

    <%= link_to 'New Notification', new_notification_path , class: 'btn btn-default'%>

  </div>
</div>

app/views/notifications/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      New Notification
      <small>New Notification</small>
    </h1>
    <p id="notice"><%= notice %></p>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-dashboard"></i>  <%= link_to 'Notifications', notifications_path %>
      </li>
      <li class="active">
        <i class="fa fa-file"></i> New Notification
      </li>
    </ol>
  </div>
</div>

<%= render 'form' %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Enterprise:</strong>
  <%= @notification.enterprise %>
</p>

<p>
  <strong>Text:</strong>
  <%= @notification.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @notification.date %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>