config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/login')

  constraints :format => 'html' do
    as :user do
      get 'login' => 'devise/sessions#new'
    end

    devise_for :users, only: :sessions
    devise_for :admins, only: :sessions

    authenticate :admin do

      devise_for :users, skip: :sessions
      devise_for :admins, skip: :sessions
      resources :enterprises, except: [:edit, :update]
    end

    authenticate :user do
      resources :notifications
      resources :devices
      resources :feeds
      resources :masks
      resources :agendas
      resources :enterprises, only: [:edit, :update]
      get 'info' => 'enterprises#edit', as: :info
    end
  end

  apipie

  namespace :api, defaults: {format: 'json'} do
    get 'enterprises/:enterprise_id/feed' => 'enterprises#feed'
    get 'enterprises/:enterprise_id/agenda' => 'enterprises#agenda'
    get 'enterprises/:enterprise_id/masks' => 'enterprises#masks'
    get 'enterprises/:enterprise_id/notifications' => 'enterprises#notifications'
    get 'enterprises/:enterprise_id/info' => 'enterprises#info'
    post 'enterprises/:enterprise_id/devices' => 'enterprises#new_device'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourClub</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'sb-admin' %>
  <%= csrf_meta_tags %>
</head>

<body>

<div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">YourClub Admin</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
      <li class="dropdown">
        <% unless current_user.nil? %>
            <%= link_to destroy_user_session_path, :method => :delete do %>
                <i class="fa fa-fw fa-power-off"></i> Log Out
            <% end %>
        <% end %>
        <% unless current_admin.nil? %>
            <%= link_to destroy_admin_session_path, :method => :delete do %>
                <i class="fa fa-fw fa-power-off"></i> Log Out
            <% end %>
        <% end %>
      </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li class="active">
          <%= link_to feeds_path do %>
              <i class='fa fa-fw fa-dashboard'></i> Feed
          <% end %>
        </li>
        <li>
          <%= link_to agendas_path do %>
              <i class='fa fa-fw fa-dashboard'></i> Agenda
          <% end %>
        </li>
        <li>
          <%= link_to masks_path do %>
              <i class='fa fa-fw fa-dashboard'></i> Masks
          <% end %>
        </li>
        <li>
          <%= link_to notifications_path do %>
              <i class='fa fa-fw fa-dashboard'></i> Notifications
          <% end %>
        </li>
        <li>
          <%= link_to info_url do %>
              <i class='fa fa-fw fa-dashboard'></i> Info
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </nav>

  <div id="page-wrapper">

    <div class="container-fluid">
      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <!-- /.container-fluid -->

  </div>
  <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

</body>
</html>